import { createContext, useContext, useState, useEffect } from 'react'

export const LANGUAGES = [
  { code: 'en', name: 'English', nativeName: 'English', flag: 'EN' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी', flag: 'HI' },
  { code: 'pa', name: 'Punjabi', nativeName: 'ਪੰਜਾਬੀ', flag: 'PA' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराठी', flag: 'MR' },
  { code: 'gu', name: 'Gujarati', nativeName: 'ગુજરાતી', flag: 'GU' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা', flag: 'BN' },
]

export const TRANSLATIONS = {
  en: {
    brand_tagline: 'Move Freight, Not Air',
    nav_browse: 'Browse Routes',
    nav_my_bookings: 'My Bookings',
    nav_driver_terminal: 'Driver Terminal',
    nav_profile: 'Profile',
    nav_login: 'Sign In',
    nav_register: 'Get Started',
    nav_logout: 'Sign Out',
    hero_title: 'Trucks are already going your way.',
    hero_subtitle:
      'Enroute connects commercial truck drivers with spare cargo space to businesses & shippers needing fast, affordable courier & freight delivery.',
    hero_cta_browse: 'Explore Live Routes',
    hero_cta_driver: 'List Your Truck Capacity',
    stat_freight_saved: 'Freight Cost Saved',
    stat_verified_trucks: 'Verified Fleet Drivers',
    stat_active_corridors: 'Active Interstate Routes',
    stat_carbon_reduction: 'CO₂ Emissions Reduced',
    search_title: 'Find Available Cargo Space Along Interstate Corridors',
    search_origin: 'From Origin (e.g. Delhi)',
    search_destination: 'To Destination (e.g. Mumbai)',
    search_truck_type: 'Truck Type (e.g. Tata 407)',
    search_clear: 'Clear Filters',
    search_loading: 'Loading available routes…',
    search_no_results: 'No active routes found matching your criteria.',
    search_no_results_desc: 'Try broadening your search filters or check back shortly.',
    card_space_available: 'Spare Capacity',
    card_departure: 'Departure',
    card_rate_km: 'per km',
    card_flat_rate: 'Flat rate',
    card_view_details: 'View Corridor & Book',
    badge_driver: 'Driver',
    badge_shipper: 'Shipper',
    badge_active: 'Active',
    badge_confirmed: 'Confirmed',
    badge_pending: 'Pending Approval',
    badge_completed: 'Delivered',
    badge_cancelled: 'Cancelled',
    login_welcome: 'Welcome Back to Enroute',
    login_sub: 'Sign in to access your freight bookings and route listings.',
    login_email: 'Email Address',
    login_password: 'Password',
    login_btn: 'Sign In',
    login_no_account: "Don't have an account?",
    login_register_link: 'Create an account',
    register_title: 'Create Your Enroute Account',
    register_sub: 'Join thousands of shippers and truck drivers optimizing logistics across India.',
    register_role_shipper: 'Ship Goods / Cargo',
    register_role_shipper_desc: 'Book spare capacity on trucks already traveling your route.',
    register_role_driver: 'I Have a Truck / Fleet',
    register_role_driver_desc: 'List unused cargo space on scheduled trips and earn extra revenue.',
    register_name: 'Full Name / Contact Person',
    register_phone: 'Phone / Mobile Number',
    register_company: 'Company / Business Name (Optional)',
    register_btn: 'Complete Registration',
    register_already_account: 'Already have an account?',
    footer_desc:
      'Enroute is an intelligent logistics freight optimization platform built for Smart India Hackathon 2026. Reducing empty truck runs, optimizing highway cargo, and lowering carbon emissions.',
    footer_quick_links: 'Quick Navigation',
    footer_driver_portal: 'Driver Network',
    footer_shipper_portal: 'Shipper Services',
    footer_rights: 'All rights reserved. Built for Smart India Hackathon 2026.',
    demo_badge: '1-Click Demo Fast Track',
    demo_driver_btn: 'Test as Driver (Rajesh)',
    demo_shipper_btn: 'Test as Shipper (Pooja)',
  },
  hi: {
    brand_tagline: 'खाली ट्रक नहीं, पूरा माल',
    nav_browse: 'मार्ग खोजें',
    nav_my_bookings: 'मेरी बुकिंग',
    nav_driver_terminal: 'ड्राइवर टर्मिनल',
    nav_profile: 'प्रोफ़ाइल',
    nav_login: 'लॉग इन',
    nav_register: 'शुरू करें',
    nav_logout: 'लॉग आउट',
    hero_title: 'ट्रक पहले से ही आपके रास्ते जा रहे हैं।',
    hero_subtitle:
      'Enroute खाली जगह वाले वाणिज्यिक ट्रकों को व्यापारियों और पार्सल भेजने वालों से जोड़ता है ताकि माल ढुलाई तेज और सस्ती हो सके।',
    hero_cta_browse: 'सक्रिय मार्ग देखें',
    hero_cta_driver: 'अपनी खाली क्षमता जोड़ें',
    stat_freight_saved: 'भाड़ा बचत',
    stat_verified_trucks: 'सत्यापित ड्राइवर',
    stat_active_corridors: 'सक्रिय राजमार्ग मार्ग',
    stat_carbon_reduction: 'कार्बन उत्सर्जन में कमी',
    search_title: 'राजमार्गों पर उपलब्ध खाली ट्रक क्षमता खोजें',
    search_origin: 'कहाँ से (उदा. दिल्ली)',
    search_destination: 'कहाँ तक (उदा. मुंबई)',
    search_truck_type: 'ट्रक प्रकार (उदा. टाटा 407)',
    search_clear: 'फ़िल्टर हटाएं',
    search_loading: 'उपलब्ध मार्ग लोड हो रहे हैं…',
    search_no_results: 'कोई सक्रिय मार्ग नहीं मिला।',
    search_no_results_desc: 'कृपया फ़िल्टर बदल कर देखें या बाद में पुनः प्रयास करें।',
    card_space_available: 'उपलब्ध जगह',
    card_departure: 'प्रस्थान समय',
    card_rate_km: 'प्रति किमी',
    card_flat_rate: 'कुल भाड़ा',
    card_view_details: 'विवरण देखें व बुक करें',
    badge_driver: 'ड्राइवर',
    badge_shipper: 'ग्राहक / व्यापारी',
    badge_active: 'सक्रिय',
    badge_confirmed: 'स्वीकृत',
    badge_pending: 'मंजूरी लंबित',
    badge_completed: 'डिलीवर हुआ',
    badge_cancelled: 'रद्द',
    login_welcome: 'Enroute में पुनः स्वागत है',
    login_sub: 'अपनी बुकिंग और रूट लिस्टिंग देखने के लिए लॉग इन करें।',
    login_email: 'ईमेल पता',
    login_password: 'पासवर्ड',
    login_btn: 'साइन इन करें',
    login_no_account: 'खाता नहीं है?',
    login_register_link: 'नया खाता बनाएं',
    register_title: 'अपना Enroute खाता बनाएं',
    register_sub: 'भारत भर में ढुलाई खर्च बचाने वाले हजारों व्यापारियों और ड्राइवरों से जुड़ें।',
    register_role_shipper: 'माल / सामान भेजना है',
    register_role_shipper_desc: 'जा रहे ट्रकों में खाली जगह बुक करें और पैसे बचाएं।',
    register_role_driver: 'मेरे पास ट्रक / वाहन है',
    register_role_driver_desc: 'खाली जगह लिस्ट करें और हर ट्रिप पर अतिरिक्त कमाई करें।',
    register_name: 'पूरा नाम / संपर्क व्यक्ति',
    register_phone: 'मोबाइल नंबर',
    register_company: 'कंपनी / व्यापार का नाम (वैकल्पिक)',
    register_btn: 'पंजीकरण पूरा करें',
    register_already_account: 'पहले से पंजीकृत हैं?',
    footer_desc:
      'Enroute स्मार्ट इंडिया हैकथॉन 2026 के तहत खाली ट्रकों को भरने और लॉजिस्टिक्स की लागत कम करने वाला आधुनिक मंच है।',
    footer_quick_links: 'महत्वपूर्ण लिंक',
    footer_driver_portal: 'ड्राइवर नेटवर्क',
    footer_shipper_portal: 'व्यापारी सेवाएं',
    footer_rights: 'सर्वाधिकार सुरक्षित। स्मार्ट इंडिया हैकथॉन 2026 के लिए निर्मित।',
    demo_badge: '1-क्लिक त्वरित डेमो लॉगिन',
    demo_driver_btn: 'ड्राइवर के रूप में देखें (राजेश)',
    demo_shipper_btn: 'व्यापारी के रूप में देखें (पूजा)',
  },
  pa: {
    brand_tagline: 'ਸਹੀ ਮਾਲ, ਸਹੀ ਰਸਤਾ',
    nav_browse: 'ਰੂਟ ਲੱਭੋ',
    nav_my_bookings: 'ਮੇਰੀਆਂ ਬੁਕਿੰਗਾਂ',
    nav_driver_terminal: 'ਡਰਾਈਵਰ ਟਰਮੀਨਲ',
    nav_profile: 'ਪ੍ਰੋਫਾਈਲ',
    nav_login: 'ਲਾਗ ਇਨ',
    nav_register: 'ਸ਼ੁਰੂ ਕਰੋ',
    nav_logout: 'ਲਾਗ ਆਊਟ',
    hero_title: 'ਟਰੱਕ ਪਹਿਲਾਂ ਹੀ ਤੁਹਾਡੇ ਰੂਟ ਤੇ ਜਾ ਰਹੇ ਹਨ।',
    hero_subtitle: 'Enroute ਖਾਲੀ ਥਾਂ ਵਾਲੇ ਟਰੱਕਾਂ ਨੂੰ ਵਪਾਰੀਆਂ ਨਾਲ ਜੋੜਦਾ ਹੈ ਤਾਂ ਜੋ ਮਾਲ ਕਿਫਾਇਤੀ ਅਤੇ ਤੇਜ਼ੀ ਨਾਲ ਪਹੁੰਚ ਸਕੇ।',
    hero_cta_browse: 'ਲਾਈਵ ਰੂਟ ਵੇਖੋ',
    hero_cta_driver: 'ਆਪਣੀ ਖਾਲੀ ਥਾਂ ਸ਼ਾਮਲ ਕਰੋ',
    stat_freight_saved: 'ਕਿਰਾਇਆ ਬੱਚਤ',
    stat_verified_trucks: 'ਪ੍ਰਮਾਣਿਤ ਡਰਾਈਵਰ',
    stat_active_corridors: 'ਸਰਗਰਮ ਰੂਟ',
    stat_carbon_reduction: 'ਕਾਰਬਨ ਨਿਕਾਸ ਘੱਟ',
    search_title: 'ਹਾਈਵੇ ਤੇ ਉਪਲਬਧ ਖਾਲੀ ਟਰੱਕ ਥਾਂ ਲੱਭੋ',
    search_origin: 'ਕਿੱਥੋਂ (ਉਦਾ. ਦਿੱਲੀ)',
    search_destination: 'ਕਿੱਥੇ (ਉਦਾ. ਲੁਧਿਆਣਾ)',
    search_truck_type: 'ਟਰੱਕ ਕਿਸਮ (ਉਦਾ. ਟਾਟਾ 407)',
    search_clear: 'ਫਿਲਟਰ ਸਾਫ਼ ਕਰੋ',
    search_loading: 'ਰੂਟ ਲੋਡ ਹੋ ਰਹੇ ਹਨ…',
    search_no_results: 'ਕੋਈ ਸਰਗਰਮ ਰੂਟ ਨਹੀਂ ਮਿਲਿਆ।',
    search_no_results_desc: 'ਕਿਰਪਾ ਕਰਕੇ ਫਿਲਟਰ ਬਦਲੋ ਜਾਂ ਬਾਅਦ ਵਿੱਚ ਕੋਸ਼ਿਸ਼ ਕਰੋ।',
    card_space_available: 'ਉਪਲਬਧ ਥਾਂ',
    card_departure: 'ਰਵਾਨਗੀ ਸਮਾਂ',
    card_rate_km: 'ਪ੍ਰਤੀ ਕਿਮੀ',
    card_flat_rate: 'ਕੁੱਲ ਕਿਰਾਇਆ',
    card_view_details: 'ਵੇਰਵੇ ਵੇਖੋ ਤੇ ਬੁੱਕ ਕਰੋ',
    badge_driver: 'ਡਰਾਈਵਰ',
    badge_shipper: 'ਗਾਹਕ / ਵਪਾਰੀ',
    badge_active: 'ਸਰਗਰਮ',
    badge_confirmed: 'ਮਨਜ਼ੂਰਸ਼ੁਦਾ',
    badge_pending: 'ਬਕਾਇਆ',
    badge_completed: 'ਡਿਲੀਵਰ ਹੋਇਆ',
    badge_cancelled: 'ਰੱਦ',
    login_welcome: 'Enroute ਵਿੱਚ ਜੀ ਆਇਆਂ ਨੂੰ',
    login_sub: 'ਆਪਣੀਆਂ ਬੁਕਿੰਗਾਂ ਅਤੇ ਰੂਟ ਵੇਖਣ ਲਈ ਲਾਗ ਇਨ ਕਰੋ।',
    login_email: 'ਈਮੇਲ ਪਤਾ',
    login_password: 'ਪਾਸਵਰਡ',
    login_btn: 'ਸਾਈਨ ਇਨ ਕਰੋ',
    login_no_account: 'ਖਾਤਾ ਨਹੀਂ ਹੈ?',
    login_register_link: 'ਨਵਾਂ ਖਾਤਾ ਬਣਾਓ',
    register_title: 'ਆਪਣਾ Enroute ਖਾਤਾ ਬਣਾਓ',
    register_sub: 'ਭਾਰਤ ਭਰ ਦੇ ਹਜ਼ਾਰਾਂ ਡਰਾਈਵਰਾਂ ਅਤੇ ਵਪਾਰੀਆਂ ਨਾਲ ਜੁੜੋ।',
    register_role_shipper: 'ਮਾਲ / ਸਾਮਾਨ ਭੇਜਣਾ ਹੈ',
    register_role_shipper_desc: 'ਜਾ ਰਹੇ ਟਰੱਕਾਂ ਵਿੱਚ ਖਾਲੀ ਥਾਂ ਬੁੱਕ ਕਰੋ।',
    register_role_driver: 'ਮੇਰੇ ਕੋਲ ਟਰੱਕ ਹੈ',
    register_role_driver_desc: 'ਖਾਲੀ ਥਾਂ ਲਿਸਟ ਕਰੋ ਅਤੇ ਵਾਧੂ ਕਮਾਈ ਕਰੋ।',
    register_name: 'ਪੂਰਾ ਨਾਮ',
    register_phone: 'ਮੋਬਾਈਲ ਨੰਬਰ',
    register_company: 'ਕੰਪਨੀ ਦਾ ਨਾਮ (ਵਿਕਲਪਿਕ)',
    register_btn: 'ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਪੂਰੀ ਕਰੋ',
    register_already_account: 'ਪਹਿਲਾਂ ਹੀ ਰਜਿਸਟਰਡ ਹੋ?',
    footer_desc: 'Enroute ਸਮਾਰਟ ਇੰਡੀਆ ਹੈਕਾਥੌਨ 2026 ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ ਲੌਜਿਸਟਿਕਸ ਪਲੇਟਫਾਰਮ ਹੈ।',
    footer_quick_links: 'ਜ਼ਰੂਰੀ ਲਿੰਕ',
    footer_driver_portal: 'ਡਰਾਈਵਰ ਨੈੱਟਵਰਕ',
    footer_shipper_portal: 'ਵਪਾਰੀ ਸੇਵਾਵਾਂ',
    footer_rights: 'ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ। ਸਮਾਰਟ ਇੰਡੀਆ ਹੈਕਾਥੌਨ 2026 ਲਈ ਤਿਆਰ ਕੀਤਾ ਗਿਆ।',
    demo_badge: '1-ਕਲਿੱਕ ਡੈਮੋ ਲਾਗਇਨ',
    demo_driver_btn: 'ਡਰਾਈਵਰ ਵਜੋਂ ਟੈਸਟ ਕਰੋ (ਰਾਜੇਸ਼)',
    demo_shipper_btn: 'ਵਪਾਰੀ ਵਜੋਂ ਟੈਸਟ ਕਰੋ (ਪੂਜਾ)',
  },
  mr: {
    brand_tagline: 'रिक्त जागा नाही, पूर्ण वाहतूक',
    nav_browse: 'मार्ग शोधा',
    nav_my_bookings: 'माझी बुकिंग',
    nav_driver_terminal: 'चालक टर्मिनल',
    nav_profile: 'प्रोफाइल',
    nav_login: 'लॉग इन',
    nav_register: 'सुरू करा',
    nav_logout: 'लॉग आउट',
    hero_title: 'ट्रक आधीच तुमच्या मार्गाने जात आहेत.',
    hero_subtitle: 'Enroute मोकळी जागा असलेल्या ट्रक्सना माल पाठवणाऱ्या व्यापाऱ्यांशी जोडते.',
    hero_cta_browse: 'मार्ग तपासा',
    hero_cta_driver: 'ट्रक क्षमता जोडा',
    stat_freight_saved: 'वाहतूक खर्च बचत',
    stat_verified_trucks: 'सत्यापित चालक',
    stat_active_corridors: 'सक्रिय मार्ग',
    stat_carbon_reduction: 'कार्बन उत्सर्जन घट',
    search_title: 'महामार्गांवर उपलब्ध मोकळी जागा शोधा',
    search_origin: 'कुठून (उदा. मुंबई)',
    search_destination: 'कुठे (उदा. पुणे)',
    search_truck_type: 'ट्रक प्रकार (उदा. टाटा 407)',
    search_clear: 'फिल्टर साफ करा',
    search_loading: 'मार्ग लोड होत आहेत…',
    search_no_results: 'कोणताही मार्ग आढळला नाही.',
    search_no_results_desc: 'कृपया पुन्हा प्रयत्न करा.',
    card_space_available: 'उपलब्ध जागा',
    card_departure: 'प्रस्थान वेळ',
    card_rate_km: 'प्रति किमी',
    card_flat_rate: 'एकूण दर',
    card_view_details: 'तपशील व बुकिंग',
    badge_driver: 'चालक',
    badge_shipper: 'ग्राहक / व्यापारी',
    badge_active: 'सक्रिय',
    badge_confirmed: 'पुष्टी झाली',
    badge_pending: 'प्रलंबित',
    badge_completed: 'पोहोचवले',
    badge_cancelled: 'रद्द',
    login_welcome: 'Enroute मध्ये आपले स्वागत आहे',
    login_sub: 'तुमची बुकिंग पाहण्यासाठी साइन इन करा.',
    login_email: 'ईमेल पत्ता',
    login_password: 'पासवर्ड',
    login_btn: 'साइन इन करा',
    login_no_account: 'खाते नाही?',
    login_register_link: 'नवीन खाते तयार करा',
    register_title: 'नवीन खाते तयार करा',
    register_sub: 'लॉजिस्टिक्स सुलभ करण्यासाठी Enroute शी जोडा.',
    register_role_shipper: 'माल पाठवायचा आहे',
    register_role_shipper_desc: 'ट्रकमधील रिकामी जागा बुक करा.',
    register_role_driver: 'माझ्याकडे ट्रक आहे',
    register_role_driver_desc: 'रिकामी जागा नोंदवा आणि अधिक कमाई करा.',
    register_name: 'पूर्ण नाव',
    register_phone: 'मोबाईल नंबर',
    register_company: 'कंपनीचे नाव (पर्यायी)',
    register_btn: 'नोंदणी पूर्ण करा',
    register_already_account: 'आधीच नोंदणीकृत आहात?',
    footer_desc: 'Enroute स्मार्ट इंडिया हॅकाथॉन 2026 साठी लॉजिस्टिक्स प्लॅटफॉर्म.',
    footer_quick_links: 'महत्त्वाचे दुवे',
    footer_driver_portal: 'चालक नेटवर्क',
    footer_shipper_portal: 'व्यापारी सेवा',
    footer_rights: 'सर्व हक्क राखीव. स्मार्ट इंडिया हॅकाथॉन 2026.',
    demo_badge: '1-क्लिक डेमो लॉगिन',
    demo_driver_btn: 'चालक म्हणून पहा (राजेश)',
    demo_shipper_btn: 'व्यापारी म्हणून पहा (पूजा)',
  },
  gu: {
    brand_tagline: 'યોગ્ય ભાડું, યોગ્ય માર્ગ',
    nav_browse: 'રૂટ શોધો',
    nav_my_bookings: 'મારી બુકિંગ',
    nav_driver_terminal: 'ડ્રાઇવર ટર્મિનલ',
    nav_profile: 'પ્રોફાઇલ',
    nav_login: 'લૉગ ઇન',
    nav_register: 'શરૂ કરો',
    nav_logout: 'લૉગ આઉટ',
    hero_title: 'ટ્રક પહેલેથી જ તમારા રસ્તે જઈ રહ્યા છે.',
    hero_subtitle: 'Enroute ખાલી જગ્યા ધરાવતા ટ્રક ડ્રાઇવરોને વેપારીઓ સાથે જોડે છે.',
    hero_cta_browse: 'રૂટ જુઓ',
    hero_cta_driver: 'ખાલી ક્ષમતા ઉમેરો',
    stat_freight_saved: 'ભાડા બચત',
    stat_verified_trucks: 'ચકાસાયેલ ડ્રાઇવરો',
    stat_active_corridors: 'સક્રિય રૂટ્સ',
    stat_carbon_reduction: 'કાર્બન ઉત્સર્જનમાં ઘટાડો',
    search_title: 'હાઇવે પર ઉપલબ્ધ ખાલી જગ્યા શોધો',
    search_origin: 'ક્યાંથી (દા.ત. સુરત)',
    search_destination: 'ક્યાં સુધી (દા.ત. અમદાવાદ)',
    search_truck_type: 'ટ્રકનો પ્રકાર (દા.ત. ટાટા 407)',
    search_clear: 'ફિલ્ટર સાફ કરો',
    search_loading: 'રૂટ લોડ થઈ રહ્યા છે…',
    search_no_results: 'કોઈ રૂટ મળ્યો નથી.',
    search_no_results_desc: 'કૃપા કરીને ફરી પ્રયાસ કરો.',
    card_space_available: 'ઉપલબ્ધ જગ્યા',
    card_departure: 'પ્રસ્થાન સમય',
    card_rate_km: 'પ્રતિ કિમી',
    card_flat_rate: 'કુલ ભાડું',
    card_view_details: 'વિગતો જુઓ અને બુક કરો',
    badge_driver: 'ડ્રાઇવર',
    badge_shipper: 'ગ્રાહક / વેપારી',
    badge_active: 'સક્રિય',
    badge_confirmed: 'કન્ફર્મ',
    badge_pending: 'બાકી',
    badge_completed: 'ડિલિવર થયું',
    badge_cancelled: 'રદ',
    login_welcome: 'Enroute માં સ્વાગત છે',
    login_sub: 'તમારા રૂટ અને બુકિંગ જોવા માટે લૉગ ઇન કરો.',
    login_email: 'ઇમેઇલ',
    login_password: 'પાસવર્ડ',
    login_btn: 'સાઇન ઇન કરો',
    login_no_account: 'ખાતું નથી?',
    login_register_link: 'નવું ખાતું બનાવો',
    register_title: 'Enroute ખાતું બનાવો',
    register_sub: 'હજારો વેપારીઓ અને ડ્રાઇવરો સાથે જોડાઓ.',
    register_role_shipper: 'માલ મોકલવો છે',
    register_role_shipper_desc: 'ખાલી જગ્યા બુક કરો અને પૈસા બચાવો.',
    register_role_driver: 'મારી પાસે ટ્રક છે',
    register_role_driver_desc: 'ખાલી જગ્યા લિસ્ટ કરો અને વધારાની કમાણી કરો.',
    register_name: 'પૂરું નામ',
    register_phone: 'મોબાઇલ નંબર',
    register_company: 'કંપનીનું નામ (વૈકલ્પિક)',
    register_btn: 'નોંધણી પૂર્ણ કરો',
    register_already_account: 'પહેલેથી નોંધાયેલા છો?',
    footer_desc: 'Enroute સ્માર્ટ ઇન્ડિયા હેકાથોન 2026 માટે લોજિસ્ટિક્સ પ્લેટફોર્મ.',
    footer_quick_links: 'મહત્વપૂર્ણ લિંક્સ',
    footer_driver_portal: 'ડ્રાઇવર નેટવર્ક',
    footer_shipper_portal: 'વેપારી સેવાઓ',
    footer_rights: 'સર્વાધિકાર સુરક્ષિત. સ્માર્ટ ઇન્ડિયા હેકાથોન 2026.',
    demo_badge: '1-ક્લિક ડેમો લૉગિન',
    demo_driver_btn: 'ડ્રાઇવર તરીકે જુઓ (રાજેશ)',
    demo_shipper_btn: 'વેપારી તરીકે જુઓ (પૂજા)',
  },
  bn: {
    brand_tagline: 'সঠিক মালবাহী, সঠিক পথ',
    nav_browse: 'রুট খুঁজুন',
    nav_my_bookings: 'আমার বুকিং',
    nav_driver_terminal: 'ড্রাইভার টার্মিনাল',
    nav_profile: 'প্রোফাইল',
    nav_login: 'লগ ইন',
    nav_register: 'শুরু করুন',
    nav_logout: 'লগ আউট',
    hero_title: 'ট্রাক ইতিমধ্যেই আপনার রুটে যাচ্ছে।',
    hero_subtitle: 'Enroute খালি জায়গা থাকা ট্রাকগুলোকে ব্যবসায়ীদের সাথে যুক্ত করে কম খরচে পণ্য পরিবহনের সুযোগ দেয়।',
    hero_cta_browse: 'সক্রিয় রুট দেখুন',
    hero_cta_driver: 'আপনার ট্রাক যোগ করুন',
    stat_freight_saved: 'ভাড়া সাশ্রয়',
    stat_verified_trucks: 'যাচাইকৃত ড্রাইভার',
    stat_active_corridors: 'সক্রিয় রুট',
    stat_carbon_reduction: 'কার্বন নির্গমন হ্রাস',
    search_title: 'হাইওয়েতে উপলব্ধ ট্রাকের খালি জায়গা খুঁজুন',
    search_origin: 'কোথা থেকে (উদা. কলকাতা)',
    search_destination: 'কোথায় (উদা. শিলিগুড়ি)',
    search_truck_type: 'ট্রাকের ধরন (উদা. টাটা 407)',
    search_clear: 'ফিল্টার মুছুন',
    search_loading: 'রুট লোড হচ্ছে…',
    search_no_results: 'কোনো রুট পাওয়া যায়নি।',
    search_no_results_desc: 'অনুগ্রহ করে আবার চেষ্টা করুন।',
    card_space_available: 'উপলব্ধ জায়গা',
    card_departure: 'যাত্রার সময়',
    card_rate_km: 'প্রতি কিমি',
    card_flat_rate: 'মোট ভাড়া',
    card_view_details: 'বিস্তারিত দেখুন ও বুক করুন',
    badge_driver: 'ড্রাইভার',
    badge_shipper: 'গ্রাহক / ব্যবসায়ী',
    badge_active: 'সক্রিয়',
    badge_confirmed: 'নিশ্চিত',
    badge_pending: 'অপেক্ষারত',
    badge_completed: 'ডেলিভারি হয়েছে',
    badge_cancelled: 'বাতিল',
    login_welcome: 'Enroute-এ স্বাগতম',
    login_sub: 'আপনার বুকিং দেখতে সাইন ইন করুন।',
    login_email: 'ইমেল ঠিকানা',
    login_password: 'পাসওয়ার্ড',
    login_btn: 'সাইন ইন করুন',
    login_no_account: 'অ্যাকাউন্ট নেই?',
    login_register_link: 'নতুন অ্যাকাউন্ট তৈরি করুন',
    register_title: 'আপনার Enroute অ্যাকাউন্ট তৈরি করুন',
    register_sub: 'হাজার হাজার ব্যবসায়ী ও ড্রাইভারদের সাথে যুক্ত হন।',
    register_role_shipper: 'পণ্য পাঠাতে চান',
    register_role_shipper_desc: 'খালি জায়গা বুক করুন ও খরচ বাঁচান।',
    register_role_driver: 'আমার ট্রাক আছে',
    register_role_driver_desc: 'খালি জায়গা তালিকাভুক্ত করুন ও অতিরিক্ত আয় করুন।',
    register_name: 'সম্পূর্ণ নাম',
    register_phone: 'মোবাইল নম্বর',
    register_company: 'কোম্পানির নাম (ঐচ্ছিক)',
    register_btn: 'নিবন্ধন সম্পন্ন করুন',
    register_already_account: 'ইতিমধ্যেই নিবন্ধিত?',
    footer_desc: 'Enroute স্মার্ট ইন্ডিয়া হ্যাকাথন ২০২৬ এর জন্য লজিস্টিক প্ল্যাটফর্ম।',
    footer_quick_links: 'গুরুত্বপূর্ণ লিঙ্ক',
    footer_driver_portal: 'ড্রাইভার নেটওয়ার্ক',
    footer_shipper_portal: 'ব্যবসায়ী পরিষেবা',
    footer_rights: 'সর্বস্বত্ব সংরক্ষিত। স্মার্ট ইন্ডিয়া হ্যাকাথন ২০২৬।',
    demo_badge: '১-ক্লিক ডেমো লগইন',
    demo_driver_btn: 'ড্রাইভার হিসেবে দেখুন (রাজেশ)',
    demo_shipper_btn: 'ব্যবসায়ী হিসেবে দেখুন (পূজা)',
  },
}

const LanguageContext = createContext(null)

export function LanguageProvider({ children }) {
  const [lang, setLangState] = useState(() => {
    return localStorage.getItem('enroute_language') || 'en'
  })

  const setLang = (code) => {
    if (TRANSLATIONS[code]) {
      setLangState(code)
      localStorage.setItem('enroute_language', code)
    }
  }

  const t = (key, fallback) => {
    const currentDict = TRANSLATIONS[lang] || TRANSLATIONS.en
    if (currentDict && currentDict[key]) {
      return currentDict[key]
    }
    const defaultDict = TRANSLATIONS.en
    if (defaultDict && defaultDict[key]) {
      return defaultDict[key]
    }
    return fallback || key
  }

  const currentLanguage = LANGUAGES.find((l) => l.code === lang) || LANGUAGES[0]

  return (
    <LanguageContext.Provider
      value={{
        lang,
        setLang,
        t,
        languages: LANGUAGES,
        currentLanguage,
      }}
    >
      {children}
    </LanguageContext.Provider>
  )
}

export const useTranslation = () => {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useTranslation must be used within a LanguageProvider')
  }
  return context
}
